# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HasuraFzf < Formula
  desc "This command has a fzf-like UI that allows you to find and run the file version used by the hasura cli command."
  homepage "https://github.com/sho-hata/hasura-fzf"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sho-hata/hasura-fzf/releases/download/v0.1.0/hasura-fzf_0.1.0_darwin_x86_64.tar.gz"
      sha256 "ffa5254fcbfc9a3c084e0ec6103ae97ca74dceab43345b82570e22250b857f30"

      def install
        bin.install "hasuraf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sho-hata/hasura-fzf/releases/download/v0.1.0/hasura-fzf_0.1.0_darwin_arm64.tar.gz"
      sha256 "908e04b6d571b0ed76d861ec0c8046fd5e32e2e053cdd14f23d0854612a7b785"

      def install
        bin.install "hasuraf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/sho-hata/hasura-fzf/releases/download/v0.1.0/hasura-fzf_0.1.0_linux_x86_64.tar.gz"
      sha256 "5220501476398a5dc82f188a31335277d7552f16c153d9b8680ccc002b6ae318"

      def install
        bin.install "hasuraf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sho-hata/hasura-fzf/releases/download/v0.1.0/hasura-fzf_0.1.0_linux_arm64.tar.gz"
      sha256 "661a3190472ffbdc6ab9a9d67b7f6783f58174ab48205d665671ad5805d032e5"

      def install
        bin.install "hasuraf"
      end
    end
  end
end
