# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hasuraf < Formula
  desc "This command has a fzf-like UI that allows you to find and run the file version used by the hasura cli command."
  homepage "https://github.com/sho-hata/hasuraf"
  version "0.1.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sho-hata/hasuraf/releases/download/v0.1.9/hasuraf_0.1.9_darwin_arm64.tar.gz"
      sha256 "e7ab843596e8e643f999f9be352c51d756079612ea2ee2b79bfd6cf0ad01de15"

      def install
        bin.install "hasuraf"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sho-hata/hasuraf/releases/download/v0.1.9/hasuraf_0.1.9_darwin_x86_64.tar.gz"
      sha256 "b3049c3ed2b6fcdeb0c268bd8bc5cf9e6e9afd84bee2bb74819f491503be44e9"

      def install
        bin.install "hasuraf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sho-hata/hasuraf/releases/download/v0.1.9/hasuraf_0.1.9_linux_arm64.tar.gz"
      sha256 "d2b5d531fa0f418ce764e4caebf81af8a773924099cbc5e0260354952fe31bab"

      def install
        bin.install "hasuraf"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sho-hata/hasuraf/releases/download/v0.1.9/hasuraf_0.1.9_linux_x86_64.tar.gz"
      sha256 "864b291d77f07f20af6339dd770b278b1a717123c6f3b9293da79ce1fb89de22"

      def install
        bin.install "hasuraf"
      end
    end
  end
end
