# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hasuraf < Formula
  desc "This command has a fzf-like UI that allows you to find and run the file version used by the hasura cli command."
  homepage "https://github.com/sho-hata/hasuraf"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sho-hata/hasuraf/releases/download/v0.2.1/hasuraf_0.2.1_darwin_arm64.tar.gz"
      sha256 "80e7a3f1ac8dc74ffdcbd7d1c839298f1ea4fcb2a4ac14e8106102ff660d62c8"

      def install
        bin.install "hasuraf"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sho-hata/hasuraf/releases/download/v0.2.1/hasuraf_0.2.1_darwin_x86_64.tar.gz"
      sha256 "9ca0e058f07c27f71afb7a26905c9dbded8dcf8fb2d4a50151adf2cbd6f7a1dd"

      def install
        bin.install "hasuraf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/sho-hata/hasuraf/releases/download/v0.2.1/hasuraf_0.2.1_linux_x86_64.tar.gz"
      sha256 "81560a83bc2e1cef9ce544cc9d10810e258e284b1893873c851b9d4bd9d644ef"

      def install
        bin.install "hasuraf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sho-hata/hasuraf/releases/download/v0.2.1/hasuraf_0.2.1_linux_arm64.tar.gz"
      sha256 "185af965d9c1db569df68f3de20441fe41562722e938433b3d15d6280fd3b2ae"

      def install
        bin.install "hasuraf"
      end
    end
  end
end
