# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HasuraFzf < Formula
  desc "This command has a fzf-like UI that allows you to find and run the file version used by the hasura cli command."
  homepage "https://github.com/sho-hata/hasura-fzf"
  version "0.1.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sho-hata/hasura-fzf/releases/download/v0.1.6/hasura-fzf_0.1.6_darwin_x86_64.tar.gz"
      sha256 "500cb4b04aa32b4c9c8ea38c862e91c141116f94578ef551b0883f0634cd9ac6"

      def install
        bin.install "hasuraf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sho-hata/hasura-fzf/releases/download/v0.1.6/hasura-fzf_0.1.6_darwin_arm64.tar.gz"
      sha256 "4a5aa919bbe0c322d9e5ea2491599fc51ac35130437ea517ee0856de18040883"

      def install
        bin.install "hasuraf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/sho-hata/hasura-fzf/releases/download/v0.1.6/hasura-fzf_0.1.6_linux_x86_64.tar.gz"
      sha256 "a71fc64d136b32574b018b6fde70df6d2fd96a606ee6cb4df35907063fdeee63"

      def install
        bin.install "hasuraf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sho-hata/hasura-fzf/releases/download/v0.1.6/hasura-fzf_0.1.6_linux_arm64.tar.gz"
      sha256 "245a42a7c1902800f6edf316dc100ce705c59bb89c0b892719fb417d5c14fc36"

      def install
        bin.install "hasuraf"
      end
    end
  end
end
